"""
Depreciation Schedule PDF Layout
=================================
Generates A4 portrait PDF of an asset's depreciation schedule.

Layout:
+--------------------------------------+
| HEADER                               |
| Company Name    | TABLEAU D'AMORT.   |
| Asset: {name}   Ref: {reference}     |
| Acquisition: {date}  Valeur: {CHF X} |
| Methode: Lineaire 60 mois           |
| Comptes: 1500 / 1509 / 6800         |
+--------------------------------------+
| TABLE                                |
| # | Date | Amort. | Cumule | VNC    |
| 1 | 30/06/21 | 431.63 | 431.63     |
| ...                                  |
+--------------------------------------+
| FOOTER                               |
| Total: {X} | VNC finale: {X}        |
| Generated by Pinnokio on {date}      |
+--------------------------------------+
"""

from io import BytesIO
from datetime import date
from decimal import Decimal
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    PageBreak,
)
from reportlab.lib.colors import HexColor


# ──────────────────────────────────────
# Theme
# ──────────────────────────────────────
ASSET_THEME = {
    "primary": HexColor("#1e40af"),       # Blue 800
    "secondary": HexColor("#1e293b"),     # Slate 800
    "light_bg": HexColor("#eff6ff"),      # Blue 50
    "border": HexColor("#bfdbfe"),        # Blue 200
    "header_bg": HexColor("#1e40af"),     # Blue 800
    "posted_bg": HexColor("#f1f5f9"),     # Slate 100
    "current_bg": HexColor("#fef3c7"),    # Amber 100
}


# ──────────────────────────────────────
# Currency formatting
# ──────────────────────────────────────
def format_currency_ch(amount: float, currency: str = "CHF") -> str:
    """Swiss format: 1'234.56 CHF"""
    formatted = f"{amount:,.2f}".replace(",", "'")
    return f"{formatted} {currency}"


def format_currency_eu(amount: float, currency: str = "EUR") -> str:
    """EU format: 1 234,56 EUR"""
    formatted = f"{amount:,.2f}"
    formatted = formatted.replace(",", "TEMP").replace(".", ",").replace("TEMP", " ")
    return f"{formatted} {currency}"


def format_currency(amount: float, currency: str = "CHF") -> str:
    if currency in ("EUR",):
        return format_currency_eu(amount, currency)
    return format_currency_ch(amount, currency)


def format_date(d: str) -> str:
    """Format ISO date string to dd.mm.yyyy"""
    if not d:
        return ""
    try:
        parts = d.split("-")
        return f"{parts[2]}.{parts[1]}.{parts[0]}"
    except (IndexError, AttributeError):
        return str(d)


# ──────────────────────────────────────
# Labels (multi-language)
# ──────────────────────────────────────
LABELS = {
    "fr": {
        "title": "TABLEAU D'AMORTISSEMENT",
        "asset": "Immobilisation",
        "reference": "Référence",
        "acquisition_date": "Date d'acquisition",
        "original_value": "Valeur d'origine",
        "salvage_value": "Valeur résiduelle",
        "depreciable_value": "Valeur amortissable",
        "method": "Méthode",
        "method_linear": "Linéaire",
        "method_degressive": "Dégressif",
        "duration": "Durée",
        "months": "mois",
        "accounts": "Comptes",
        "account_asset": "Immobilisation",
        "account_depreciation": "Amort. cumulées",
        "account_expense": "Charges amort.",
        "col_number": "#",
        "col_date": "Date",
        "col_amount": "Amortissement",
        "col_cumulated": "Amort. cumulé",
        "col_remaining": "VNC",
        "col_status": "Statut",
        "col_gl_ref": "Pièce",
        "status_posted": "Comptabilisé",
        "status_pending": "En attente",
        "total": "Total",
        "final_nbv": "VNC finale",
        "generated_by": "Généré par Pinnokio le",
        "state_draft": "Brouillon",
        "state_running": "En cours",
        "state_close": "Totalement amorti",
        "state_disposed": "Cédé",
    },
    "en": {
        "title": "DEPRECIATION SCHEDULE",
        "asset": "Fixed Asset",
        "reference": "Reference",
        "acquisition_date": "Acquisition Date",
        "original_value": "Original Value",
        "salvage_value": "Salvage Value",
        "depreciable_value": "Depreciable Value",
        "method": "Method",
        "method_linear": "Straight-line",
        "method_degressive": "Declining Balance",
        "duration": "Duration",
        "months": "months",
        "accounts": "Accounts",
        "account_asset": "Asset Account",
        "account_depreciation": "Accum. Depreciation",
        "account_expense": "Depreciation Expense",
        "col_number": "#",
        "col_date": "Date",
        "col_amount": "Depreciation",
        "col_cumulated": "Accumulated",
        "col_remaining": "NBV",
        "col_status": "Status",
        "col_gl_ref": "Entry",
        "status_posted": "Posted",
        "status_pending": "Pending",
        "total": "Total",
        "final_nbv": "Final NBV",
        "generated_by": "Generated by Pinnokio on",
        "state_draft": "Draft",
        "state_running": "Running",
        "state_close": "Fully Depreciated",
        "state_disposed": "Disposed",
    },
    "de": {
        "title": "ABSCHREIBUNGSPLAN",
        "asset": "Anlagevermögen",
        "reference": "Referenz",
        "acquisition_date": "Anschaffungsdatum",
        "original_value": "Anschaffungswert",
        "salvage_value": "Restwert",
        "depreciable_value": "Abschreibungsbetrag",
        "method": "Methode",
        "method_linear": "Linear",
        "method_degressive": "Degressiv",
        "duration": "Dauer",
        "months": "Monate",
        "accounts": "Konten",
        "account_asset": "Anlagekonto",
        "account_depreciation": "Kum. Abschreibung",
        "account_expense": "Abschreibungsaufwand",
        "col_number": "#",
        "col_date": "Datum",
        "col_amount": "Abschreibung",
        "col_cumulated": "Kumuliert",
        "col_remaining": "Buchwert",
        "col_status": "Status",
        "col_gl_ref": "Beleg",
        "status_posted": "Gebucht",
        "status_pending": "Ausstehend",
        "total": "Total",
        "final_nbv": "Buchwert Ende",
        "generated_by": "Erstellt von Pinnokio am",
        "state_draft": "Entwurf",
        "state_running": "Laufend",
        "state_close": "Voll abgeschrieben",
        "state_disposed": "Veräussert",
    },
}


def _get_labels(language: str = "fr") -> Dict[str, str]:
    return LABELS.get(language, LABELS["fr"])


# ──────────────────────────────────────
# Main generator
# ──────────────────────────────────────
def generate_depreciation_schedule_pdf(
    asset: Dict[str, Any],
    lines: List[Dict[str, Any]],
    company_name: str = "Entreprise SA",
    company_address: str = "",
    language: str = "fr",
    output: Optional[BytesIO] = None,
) -> BytesIO:
    """
    Generate a depreciation schedule PDF.

    Args:
        asset: Dict with keys: name, reference, acquisition_date, original_value,
               salvage_value, currency, method, method_number, method_period,
               account_asset_number, account_depreciation_number, account_expense_number,
               state, book_value
        lines: List of dicts with keys: line_number, depreciation_date, amount,
               cumulated_amount, remaining_value, is_posted, gl_entry_ref
        company_name: Company display name
        company_address: Company address (optional)
        language: "fr", "en", or "de"
        output: Optional BytesIO buffer

    Returns:
        BytesIO with PDF content
    """
    if output is None:
        output = BytesIO()

    lbl = _get_labels(language)
    theme = ASSET_THEME
    currency = asset.get("currency", "CHF")

    # ── Styles ──
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "AssetTitle",
        parent=styles["Heading1"],
        fontSize=16,
        textColor=theme["primary"],
        spaceAfter=2 * mm,
    )
    subtitle_style = ParagraphStyle(
        "AssetSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.grey,
    )
    header_label_style = ParagraphStyle(
        "HeaderLabel",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.grey,
    )
    header_value_style = ParagraphStyle(
        "HeaderValue",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Helvetica-Bold",
    )
    small_style = ParagraphStyle(
        "Small",
        parent=styles["Normal"],
        fontSize=7,
        leading=9,
    )
    small_right = ParagraphStyle(
        "SmallRight",
        parent=small_style,
        alignment=TA_RIGHT,
    )
    small_center = ParagraphStyle(
        "SmallCenter",
        parent=small_style,
        alignment=TA_CENTER,
    )
    small_bold = ParagraphStyle(
        "SmallBold",
        parent=small_style,
        fontName="Helvetica-Bold",
    )
    small_bold_right = ParagraphStyle(
        "SmallBoldRight",
        parent=small_bold,
        alignment=TA_RIGHT,
    )
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=7,
        textColor=colors.grey,
        alignment=TA_RIGHT,
    )

    elements = []

    # ══════════════════════════════════
    # HEADER
    # ══════════════════════════════════
    # Company + title row
    header_data = [
        [
            Paragraph(f"<b>{company_name}</b>", styles["Heading2"]),
            Paragraph(f"<b>{lbl['title']}</b>", title_style),
        ],
    ]
    if company_address:
        header_data.append([
            Paragraph(company_address.replace("\n", "<br/>"), subtitle_style),
            "",
        ])

    header_table = Table(header_data, colWidths=[9 * cm, 9 * cm])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
    ]))
    elements.append(header_table)
    elements.append(Spacer(1, 4 * mm))

    # Separator
    sep = Table([[""]], colWidths=[18 * cm])
    sep.setStyle(TableStyle([("LINEBELOW", (0, 0), (-1, -1), 2, theme["primary"])]))
    elements.append(sep)
    elements.append(Spacer(1, 4 * mm))

    # ── Asset info grid ──
    method_label = lbl["method_linear"] if asset.get("method") == "linear" else lbl["method_degressive"]
    depreciable = float(asset.get("original_value", 0)) - float(asset.get("salvage_value", 0))

    info_data = [
        # Row 1
        [
            Paragraph(f"<b>{lbl['asset']}:</b> {asset.get('name', '')}", header_value_style),
            Paragraph(f"<b>{lbl['reference']}:</b> {asset.get('reference', '—')}", header_value_style),
            Paragraph(f"<b>{lbl['method']}:</b> {method_label}", header_value_style),
        ],
        # Row 2
        [
            Paragraph(
                f"<b>{lbl['acquisition_date']}:</b> {format_date(str(asset.get('acquisition_date', '')))}",
                header_value_style,
            ),
            Paragraph(
                f"<b>{lbl['original_value']}:</b> {format_currency(float(asset.get('original_value', 0)), currency)}",
                header_value_style,
            ),
            Paragraph(
                f"<b>{lbl['duration']}:</b> {asset.get('method_number', 60)} {lbl['months']}",
                header_value_style,
            ),
        ],
        # Row 3
        [
            Paragraph(
                f"<b>{lbl['depreciable_value']}:</b> {format_currency(depreciable, currency)}",
                header_value_style,
            ),
            Paragraph(
                f"<b>{lbl['salvage_value']}:</b> {format_currency(float(asset.get('salvage_value', 0)), currency)}",
                header_value_style,
            ),
            "",
        ],
    ]

    info_table = Table(info_data, colWidths=[6.5 * cm, 6 * cm, 5.5 * cm])
    info_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("BACKGROUND", (0, 0), (-1, -1), theme["light_bg"]),
        ("BOX", (0, 0), (-1, -1), 0.5, theme["border"]),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 2 * mm))

    # Account references
    acct_text = (
        f"<b>{lbl['accounts']}:</b> "
        f"{lbl['account_asset']} {asset.get('account_asset_number', '')} | "
        f"{lbl['account_depreciation']} {asset.get('account_depreciation_number', '')} | "
        f"{lbl['account_expense']} {asset.get('account_expense_number', '')}"
    )
    elements.append(Paragraph(acct_text, header_label_style))
    elements.append(Spacer(1, 6 * mm))

    # ══════════════════════════════════
    # DEPRECIATION TABLE
    # ══════════════════════════════════
    col_widths = [1 * cm, 2.5 * cm, 3 * cm, 3 * cm, 3 * cm, 2 * cm, 3.5 * cm]

    # Header row
    table_header = [
        Paragraph(f"<b>{lbl['col_number']}</b>", small_center),
        Paragraph(f"<b>{lbl['col_date']}</b>", small_bold),
        Paragraph(f"<b>{lbl['col_amount']}</b>", small_bold_right),
        Paragraph(f"<b>{lbl['col_cumulated']}</b>", small_bold_right),
        Paragraph(f"<b>{lbl['col_remaining']}</b>", small_bold_right),
        Paragraph(f"<b>{lbl['col_status']}</b>", small_center),
        Paragraph(f"<b>{lbl['col_gl_ref']}</b>", small_bold),
    ]

    table_data = [table_header]

    # Find first unposted line index (for highlighting)
    first_unposted_idx = None
    for i, line in enumerate(lines):
        if not line.get("is_posted", False):
            first_unposted_idx = i
            break

    # Data rows
    for i, line in enumerate(lines):
        is_posted = line.get("is_posted", False)
        status_text = lbl["status_posted"] if is_posted else lbl["status_pending"]
        gl_ref = line.get("gl_entry_ref", "") or "—"

        row = [
            Paragraph(str(line.get("line_number", i + 1)), small_center),
            Paragraph(format_date(str(line.get("depreciation_date", ""))), small_style),
            Paragraph(format_currency(float(line.get("amount", 0)), currency), small_right),
            Paragraph(format_currency(float(line.get("cumulated_amount", 0)), currency), small_right),
            Paragraph(format_currency(float(line.get("remaining_value", 0)), currency), small_right),
            Paragraph(status_text, small_center),
            Paragraph(str(gl_ref), small_style),
        ]
        table_data.append(row)

    # Total row
    if lines:
        last = lines[-1]
        total_depreciation = float(last.get("cumulated_amount", 0))
        final_nbv = float(last.get("remaining_value", 0))
        total_row = [
            "",
            Paragraph(f"<b>{lbl['total']}</b>", small_bold),
            Paragraph(f"<b>{format_currency(total_depreciation, currency)}</b>", small_bold_right),
            "",
            Paragraph(f"<b>{format_currency(final_nbv, currency)}</b>", small_bold_right),
            "",
            "",
        ]
        table_data.append(total_row)

    depr_table = Table(table_data, colWidths=col_widths, repeatRows=1)

    # Styling
    style_cmds = [
        # Header
        ("BACKGROUND", (0, 0), (-1, 0), theme["header_bg"]),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 7),
        # Grid
        ("GRID", (0, 0), (-1, -1), 0.5, theme["border"]),
        # Alignment
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("LEFTPADDING", (0, 0), (-1, -1), 3),
        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
    ]

    # Alternate row colors for posted lines
    for i, line in enumerate(lines):
        row_idx = i + 1  # +1 for header
        if line.get("is_posted", False):
            style_cmds.append(("BACKGROUND", (0, row_idx), (-1, row_idx), theme["posted_bg"]))
        if first_unposted_idx is not None and i == first_unposted_idx:
            style_cmds.append(("BACKGROUND", (0, row_idx), (-1, row_idx), theme["current_bg"]))

    # Total row styling
    if lines:
        total_idx = len(lines) + 1
        style_cmds.extend([
            ("BACKGROUND", (0, total_idx), (-1, total_idx), theme["light_bg"]),
            ("LINEABOVE", (0, total_idx), (-1, total_idx), 1.5, theme["primary"]),
            ("FONTNAME", (0, total_idx), (-1, total_idx), "Helvetica-Bold"),
        ])

    depr_table.setStyle(TableStyle(style_cmds))
    elements.append(depr_table)

    # ══════════════════════════════════
    # FOOTER
    # ══════════════════════════════════
    elements.append(Spacer(1, 10 * mm))
    gen_date = date.today().strftime("%d.%m.%Y")
    elements.append(Paragraph(f"{lbl['generated_by']} {gen_date}", footer_style))

    # ── Build PDF ──
    doc = SimpleDocTemplate(
        output,
        pagesize=A4,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
    )
    doc.build(elements)
    output.seek(0)
    return output
