name: Deploy to ECS (pinnokio_microservice)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: pinnokio_microservice
  ECS_CLUSTER: pinnokio_cluster
  ECS_SERVICE: pinnokio_microservice
  ECS_TASK_FAMILY: pinnokio_microservice
  CONTAINER_NAME: pinnokio_microservice
  IMAGE_TAG: ${{ github.sha }}
  ECS_TG_ARN: arn:aws:elasticloadbalancing:us-east-1:654654322636:targetgroup/pinnokio-firebase-backend/18189f1dfb06bcef
  # Optionnel: si vous souhaitez binder automatiquement le service à un TG IP:8090
  # Fournir en secret GitHub: ECS_TG_ARN

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          echo "image=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

      - name: Prepare base64 GCP secret
        id: gcp_b64
        shell: bash
        run: |
          set -e
          python - << 'PY'
import os, base64, json
s = os.environ.get('GCP_SECRET', '')
if s:
    # Valider JSON puis encoder
    json.loads(s)
    b64 = base64.b64encode(s.encode('utf-8')).decode('utf-8')
else:
    b64 = ''
out = os.environ['GITHUB_OUTPUT']
with open(out, 'a', encoding='utf-8') as f:
    f.write(f"b64={b64}\n")
PY
        env:
          GCP_SECRET: ${{ secrets.GCP_SECRET }}

      - name: Render ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-taskdef.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          environment-variables: |
            GOOGLE_SERVICE_ACCOUNT_JSON_B64=${{ steps.gcp_b64.outputs.b64 }}

      - name: Ensure ECS service exists (create if missing)
        env:
          SUBNET_IDS: ${{ secrets.ECS_SUBNET_IDS }} # comma-separated private subnets
          SECURITY_GROUP_ID: ${{ secrets.ECS_SECURITY_GROUP_ID }}
          TG_ARN: ${{ secrets.ECS_TG_ARN }}
        run: |
          set -e
          # fallback sur la variable d'environnement globale si le secret n'est pas fourni
          if [ -z "$TG_ARN" ] && [ -n "$ECS_TG_ARN" ]; then TG_ARN="$ECS_TG_ARN"; fi
          STATUS=$(aws ecs describe-services --cluster "$ECS_CLUSTER" --services "$ECS_SERVICE" --query 'services[0].status' --output text || true)
          if [ "$STATUS" = "ACTIVE" ]; then
            echo "Service already exists"
          else
            echo "Creating ECS service $ECS_SERVICE in cluster $ECS_CLUSTER"
            if [ -n "$TG_ARN" ]; then
              aws ecs create-service \
                --cluster "$ECS_CLUSTER" \
                --service-name "$ECS_SERVICE" \
                --task-definition ${{ env.ECS_TASK_FAMILY }} \
                --desired-count 1 \
                --launch-type FARGATE \
                --load-balancers targetGroupArn=$TG_ARN,containerName=${{ env.CONTAINER_NAME }},containerPort=8090 \
                --network-configuration "awsvpcConfiguration={subnets=[$(echo $SUBNET_IDS | sed 's/,/,/g')],securityGroups=[$SECURITY_GROUP_ID],assignPublicIp=DISABLED}"
            else
              aws ecs create-service \
                --cluster "$ECS_CLUSTER" \
                --service-name "$ECS_SERVICE" \
                --task-definition ${{ env.ECS_TASK_FAMILY }} \
                --desired-count 1 \
                --launch-type FARGATE \
                --network-configuration "awsvpcConfiguration={subnets=[$(echo $SUBNET_IDS | sed 's/,/,/g')],securityGroups=[$SECURITY_GROUP_ID],assignPublicIp=DISABLED}"
            fi
          fi

      - name: Deploy Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true


